# Generated by Django 5.2.1 on 2025-05-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=100)),
                ('phone', models.CharField(default='0000000000', max_length=25)),
                ('payment_status', models.CharField(choices=[('paid', 'A payé'), ('not_paid', "N'a pas payé")], default='not_paid', max_length=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
