# Generated by Django 5.2.1 on 2025-05-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('telephone', models.CharField(default='0000000000', max_length=25)),
                ('email', models.EmailField(default='name@gmail.com', max_length=254, unique=True)),
                ('activity_type', models.CharField(choices=[('culture', 'Culture (céréales, légumes, etc.)'), ('elevage', 'Élevage (bovins, ovins, volailles...)'), ('apiculture', 'Apiculture (élevage d’abeilles)'), ('maraichage', 'Maraîchage (légumes et plantes comestibles)'), ('arboriculture', 'Arboriculture (arbres fruitiers, oliviers, etc.)'), ('autre', 'Autre')], default='culture', max_length=20)),
            ],
        ),
    ]
