apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: ghcr.io/amidimanar/auth-service:latest
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: ghcr-secret
