pipeline {
        agent {
        docker {
            image 'bitnami/kubectl:latest'  // ou une autre image docker qui contient kubectl
            args '-v /var/run/docker.sock:/var/run/docker.sock' // pour pouvoir utiliser Docker dans le container
        }
    }

    environment {
        IMAGE_NAME = "ghcr.io/amidimanar/auth-service:latest"
        PATH = "/usr/local/bin:$PATH"
    }


    stages {
        stage('Checkout') {
          steps {
                git url: 'https://github.com/amidimanar/app-manarr.git', branch: 'main'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('backend/agrovera_microservices/auth_service') {
                    sh "docker build -t $IMAGE_NAME ."
                }
            }
        }

        stage('Login to GHCR') {
            steps {
                withCredentials([string(credentialsId: 'jenkins-ghcr-token', variable: 'GITHUB_TOKEN')]) {
                    sh 'echo $GITHUB_TOKEN | docker login ghcr.io -u amidimanar --password-stdin'
                }
            }
        }

        stage('Push Image') {
            steps {
                sh "docker push $IMAGE_NAME"
            }
        }

        stage('Deploy to K3s') {
            steps {
                sh "/usr/local/bin/kubectl apply -f k8s/deployment-auth.yaml"
            }
        }
    }
}
