name: Microservices CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: coredb
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Python dependencies (Auth)
        run: |
          cd backend/microservices/auth_service
          pip install -r requirements.txt

      - name: Run backend tests (Auth)
        run: |
          cd backend/microservices/auth_service
          python -m unittest discover

      - name: Install frontend dependencies
        run: |
          cd frontend/react-website
          npm install

      - name: Run frontend tests
        run: |
          cd frontend/react-website
          npm test -- --watchAll=false
